# Generated by Django 2.1.7 on 2019-02-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='image',
        ),
        migrations.AddField(
            model_name='meme',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
